Portfolio Accessibility
Nizamuddin4493/My-Portfolio pull request #9
Opened 2021-11-09 22:07 UTC by Nizamuddin4493

In this exercise, we have to check in PP the issues below if they need any changes.

 - **Page titles** - removed the My Portfolio and changed it to my name
- **Image text alternatives** - Changed - sent me an email
- **Text headings** - changed
- **Color contrast** - no issue found
- **Resize** - no issue found
- **Interaction** - no issue found
- **Moving content** - no issue found
- **Multimedia** - N/A
- **The basic structure of the page** - no issue found

2021-11-09 22:29 UTC, omar-labana requested changes
Hi Collaborators, 

Excellent work so far! 👌
You have implemented almost all the required features. ✔️ 
There are some cases that you need to adjust but you are almost done! 😀

## Required Changes ♻️
- [ ] Your portfolio still has some contrast ratio flaws. Kindly, check [this](https://www.aditus.io/button-contrast-checker/github-com-2021-11-09-at-22-26-00-312) audit and make sure that the `Contrast Checker` is catching no flaws.
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
_N/A_

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-09 22:29 UTC, omar-labana commented on index.html
> +  <title>Nizamuddin</title>
- [ ] Kindly update your title to it adequately and briefly describes the content of the page, example:
`Nizamuddin's portifolio`
`Nizamuddin full-stack web developer`

2021-11-10 02:28 UTC, gabrielyea approved these changes
Hi @Nizamuddin4493  
![](https://media4.giphy.com/media/MAzunB1Ru6zAYlYgPD/giphy.gif)
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations and keep up the great work!

I left some `OPTIONAL` suggestions for you to try out!

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-10 02:28 UTC, gabrielyea commented on css/styles.css
> +  background: #f55800;
[OPTIONAL] I am sorry the previous review was not clear enough and didn't point where the problem was! :pray:   Great work trying to fix the contrast! Sadly the color change was not enough!. :disappointed: 

- [ ] Would you kindly fix the colors so they pass all the accessibility tests!
The contrast should have a ratio of 4.5:1, and as you can see below it doesn't meet the test requirements. :arrow_down: 
![image](https://user-images.githubusercontent.com/28903404/141035847-f830f37c-f070-4f61-b302-3439f9b9bf89.png)

You can quickly test contrast values by using [contrast](https://developer.mozilla.org/en-US/docs/Web/CSS/filter-function/contrast())
## Check it out!
![contrastChange](https://user-images.githubusercontent.com/28903404/141036860-58ad6154-3812-48af-b496-8de0205a8fc4.gif)

2021-11-10 02:28 UTC, gabrielyea commented on css/styles.css
> +  color: #f55800;
[OPTIONAL] Same issue as above :arrow_up:  . I can see you tried to fix the contrast but it wasn't enough!

- [ ] I suggest you increase the contrast by either changing the colors or by using [contrast](https://developer.mozilla.org/en-US/docs/Web/CSS/filter-function/contrast())

2021-11-10 14:45 UTC, merged